### ISSUE TITLE
MailChimp Subscribers List empty in OroCRM

### ISSUE THREAD

**Issue by victorarandaiglesias** [oroinc/OroCRMMailChimpBundle#11]
I have created a new Mailchimp integration in my OroCrm backend and  connection is checked (valid API Key). ORO daemon us running. Everything is OK at this point.
In Mailchimp a list is created correctly.
When I create a new Marketing list in Oro (contact entity and dynamic ) and try to connect it to Mailchimp, MailChimp Subscribers List is empty.

Any idea?

**Comment by mkudelya** [comment]
Hi @victorarandaiglesias 

Please try [the export](https://github.com/orocrm/OroCRMMailChimpBundle#export-logic) command.

**Comment by vbyndych** [comment]
I hope this question was solved. It has been inactive for a while so I'm closing it. Please, feel free to reopen it if you have any questions.
