### ISSUE TITLE
Unable to use MemberActivityImportStrategy with oro/platform 3.1.9

### ISSUE THREAD

**Issue by zaklina-data** [oroinc/OroCRMMailChimpBundle#13]
When I shedule and run sync I'm getting error
`In getOroMailchimp_Importexport_Strategy_MemberActivityService.php line 17:                                                                        
  [Error]                                                                                                                                
  Call to undefined method Oro\Bundle\MailChimpBundle\ImportExport\Strategy\MemberActivityImportStrategy::setRelatedEntityStateHelper() `

 Probable reason and solution: {{MemberActivityImportStrategy}} class should extend {{Oro\Bundle\ImportExportBundle\Strategy\Import\ConfigurableAddOrReplaceStrategy}} instead of {{Oro\Bundle\ImportExportBundle\Strategy\Import\AbstractImportStrategy}} as it is defined in services.yml. Or change parent in services.yml to {{oro_importexport.strategy.abstract_import_strategy}}

**Comment by anyt** [comment]
Hi @zaklina-data,

Oro supports OroCRMMailChimpBundle only till 2.6 version. Starting from 3.1 the development is being done by "H1 - Webdevelopment".
Please create an issue at https://github.com/h1-webdevelopment/crm-mail-chimp
I'm closing this one.
